### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by JFcy** [jibo27/3DGS_Hierarchical_Training#10]
When I ran the code, I meet the error like: And I have done as readme.md , update the diff-gaussian-rasterization and the code
`
          raster_settings = GaussianRasterizationSettings(
            image_height=int(viewpoint_camera.image_height),
            image_width=int(viewpoint_camera.image_width),
            tanfovx=tanfovx,
            tanfovy=tanfovy,
            bg=self.bg_color if not invert_bg_color else 1 - self.bg_color,
            scale_modifier=scaling_modifier,
            viewmatrix=viewpoint_camera.world_view_transform,
            projmatrix=viewpoint_camera.full_proj_transform,
            sh_degree=self.gaussians.active_sh_degree,
            campos=viewpoint_camera.camera_center,
            prefiltered=False,
            debug=False,
            antialiasing=False,  # Add this argument
        )
`

![Image](https://github.com/user-attachments/assets/5b68c216-93f4-4888-9941-5ba396de20a0)

**Comment by jibo27** [comment]
Hi,

Thanks for your question. Based on my experience, this is still an issue with `diff-gaussian-rasterization`. I'd recommend trying installations from these repositories one by one: `3DGS_Hierarchical_Training`, [`gaussian-splatting`](https://github.com/graphdeco-inria/gaussian-splatting), and [`CF-3DGS`](https://github.com/NVlabs/CF-3DGS).

As you have checked in the README, I encountered this bug and resolved it by using the [`gaussian-splatting`](https://github.com/graphdeco-inria/gaussian-splatting) implementation. However, since this might not be a universal solution, I suggest testing the different submodules. 

For reference, my setup uses CUDA 11.7 (I am not sure if the CUDA version matters).
1. I kept the original `submodules` folder in `3DGS_Hierarchical_Training` unchanged (or you can try replacing the folder?).  
2. Installed the module from the `gaussian-splatting` repository.  
3. Returned to the `3DGS_Hierarchical_Training` directory and successfully ran the code.  

Best Regards,
Ji Bo

**Comment by T1t2nium** [comment]
Hello author, I have the same problem. Strangely, my CUDA version is the same as yours, 11.7. All the packages in the environment are installed according to the README, and I also update diff-gaussian-rasterization according to the steps you gave, but I still face the problem of "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.87 GiB. GPU". You mentioned in the above discussion that I can install from these repositories one by one: 3DGS_Hierarchical_Training, gaussian-splatting, and CF-3DGS, but unfortunately, I have tried all the installation sources and still have the same problem.

**Comment by JFcy** [comment]
I do not know the reason, I use cuda 12.2 , and finally, I use the diff-gaussian-rasterization provided in CF-3DGS, the problem has been solved.

**Comment by T1t2nium** [comment]
> I do not know the reason, I use cuda 12.2 , and finally, I use the diff-gaussian-rasterization provided in CF-3DGS, the problem has been solved.

Thank you very much for your help. I also successfully ran the training code according to the cuda version (12.2) you gave, but the training log was only written in the output directory and the training progress was not displayed in the terminal. I don’t know if you have the same problem as me.

**Comment by T1t2nium** [comment]
> I do not know the reason, I use cuda 12.2 , and finally, I use the diff-gaussian-rasterization provided in CF-3DGS, the problem has been solved.

Thanks again, everything is working now.

**Comment by haowang020110** [comment]
Hi, I change the repo name from 3DGS_Hierarchical_Training to ht_3dgs and reinstall diff-gaussian-rasterization.
The OOM problem disapper!(haha)

**Comment by JFcy** [comment]
Hi, I saw you have type

<img width="959" height="183" alt="Image" src="https://github.com/user-attachments/assets/fd3b5051-5f33-44b2-a4ef-efb3b27a1e69" />
Have you compare random partition and evenly sampling. I previously thought that having smaller inter-frame relative displacements within the same group would be beneficial for GS training. I wonder if you have tried this approach.

**Comment by jibo27** [comment]
> Hi, I saw you have type
> 
> <img alt="Image" width="959" height="183" src="https://private-user-images.githubusercontent.com/108513335/487091459-fd3b5051-5f33-44b2-a4ef-efb3b27a1e69.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc0MTQ1MzAsIm5iZiI6MTc1NzQxNDIzMCwicGF0aCI6Ii8xMDg1MTMzMzUvNDg3MDkxNDU5LWZkM2I1MDUxLTVmMzMtNDRiMi1hNGVmLWVmYjNiMjdhMWU2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwOVQxMDM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTUzNjgzYWI0ZDRhY2YzOTg4MWVmNjdhYmU2OTk1NGYxMGJmM2YzYzAyYTY4MDAwOGY1YzdlOTk2OGRkNDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-yVYvnI-O1Zs1yxA5SBKVk2W-VWKrLmfQkB-XC0DVxg"> Have you compare random partition and evenly sampling. I previously thought that having smaller inter-frame relative displacements within the same group would be beneficial for GS training. I wonder if you have tried this approach.

Hi, I think this is an interesting question! We tried even sampling, and the results were quite similar. However, we didn’t try random partitioning.
