### ISSUE TITLE
CUDA out of Memory

### ISSUE THREAD

**Issue by XLR-man** [jibo27/3DGS_Hierarchical_Training#5]
When i run in 24GB 4090:
"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 36.19 GiB (GPU 0; 23.64 GiB total capacity; 1.58 GiB already allocated; 21.26 GiB free; 1.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
"

How can i run the code in 4090?

**Comment by XLR-man** [comment]
And i want to ask, When i run CF-3DGS in 4090, it's alright.
Why your method need more memory of GPU compared to CF-3DGS?

**Comment by jibo27** [comment]
Hi,

I also used a single 24GB A5000 GPU. Could you clarify at which stage this error occurs and share more logs? Is it during relative camera estimation, single 3DGS model training, supervision with base model, or another step?

There are several reasons for high GPU memory usage:

1. **Excessive 3D Gaussians**: The number of 3D Gaussians may become too large. You can verify this by checking the log for the number of 3D Gaussians. For a 24GB GPU, the number should be around 1.2M for the Francis dataset. If the number significantly exceeds this, it is likely causing an out-of-memory error.
2. **Base Model Storage for Distillation**: Compared to CF-3DGS, our method uses more GPU memory because we store the base models to generate pseudo-view rendered images for supervision during distillation.


Here are some potential solutions:

- **For the first issue**: Try increasing the densification interval by increasing parameters like `mss_phase1_densification_interval` and `mss_phase2_densification_interval` in the yaml file. This reduces the frequency of densification, preventing the number of 3D Gaussians from growing too quickly. Alternatively, you can set `mss_phase1_densify_until_iter_ratio` and `mss_phase2_densify_until_iter_ratio` to a value between 0 and 1. This will stop densification at an earlier stage.
- **For the second case**: Consider disabling the supervision from the base model initially. For example, set `multi_source_supervision: ""` or `multi_source_supervision: "vfi"` in the YAML file. Disabling supervision reduces GPU memory usage to a level similar to CF-3DGS. We will remove the unnecessary 3DGS models in this setting ([link](https://github.com/jibo27/3DGS_Hierarchical_Training/blob/main/trainer/ht3dgs_trainer.py#L801)). While this may slightly lower average performance, it can work well for certain scenes.
- **Rerun the code**: Sometimes, simply rerunning the process can resolve this.

In most cases, the error is caused by the number of 3D Gaussians becoming too large during training. Therefore, the second solution is often the most practical. Since I’m unsure at which step the error occurs, it would be helpful if you could share some logs for further analysis.

Best Regards,
Ji Bo

**Comment by XLR-man** [comment]
Here is the error:
```
INFO:my_logger:Train Frame 0
Traceback (most recent call last):
  File "/data/xielangren/project/3DGS_Hierarchical_Training/run.py", line 51, in <module>
    trainer.hierarchical_training()
  File "/data/xielangren/project/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 698, in hierarchical_training
    self.compute_relative_pose(fidx, fidx-1) # rel_pose: view_idx_prev --> view_idx
  File "/data/xielangren/project/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 349, in compute_relative_pose
    return self.compute_relative_pose_vfi(view_idx, view_idx_prev)
  File "/data/xielangren/project/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 403, in compute_relative_pose_vfi
    self.train_single_image_3DGS(optim_opt, viewpoint_cam, pipe, gs_render=self.gs_render_local)
  File "/data/xielangren/project/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 291, in train_single_image_3DGS
    loss, rend_dict, psnr_train = self.train_step(gs_render,
  File "/data/xielangren/project/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 102, in train_step
    render_pkg = gs_render.render(
  File "/data/xielangren/project/3DGS_Hierarchical_Training/scene/gaussian_model_ht.py", line 871, in render
    out = rasterizer(
  File "/data/xielangren/miniconda3/envs/ht3dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ht3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 213, in forward
    return rasterize_gaussians(
  File "/data/xielangren/miniconda3/envs/ht3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/data/xielangren/miniconda3/envs/ht3dgs/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/xielangren/miniconda3/envs/ht3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, depth, alpha, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 36.19 GiB (GPU 0; 23.64 GiB total capacity; 1.58 GiB already allocated; 21.26 GiB free; 1.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by jibo27** [comment]
Hi, 

Thank you for bringing this up! I was able to reproduce the error and resolve the issue.  

The problem stems from the `diff_gaussian_rasterization` package. To fix it, I uninstalled the current version and installed a new one from the [`gaussian-splatting`](https://github.com/graphdeco-inria/gaussian-splatting/tree/main) repository.  

Here are the steps I took to resolve the issue:  

**Step 1: Uninstall the current package and install the new one.**  
```bash
git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive
cd gaussian-splatting
pip uninstall diff_gaussian_rasterization
pip install submodules/diff-gaussian-rasterization
```

**Step 2: Add the `antialiasing=False` argument.**  
I added this argument in the following [location](https://github.com/jibo27/3DGS_Hierarchical_Training/blob/main/scene/gaussian_model_ht.py#L809) in the code:  
```python
raster_settings = GaussianRasterizationSettings(
    image_height=int(viewpoint_camera.image_height),
    image_width=int(viewpoint_camera.image_width),
    tanfovx=tanfovx,
    tanfovy=tanfovy,
    bg=self.bg_color if not invert_bg_color else 1 - self.bg_color,
    scale_modifier=scaling_modifier,
    viewmatrix=viewpoint_camera.world_view_transform,
    projmatrix=viewpoint_camera.full_proj_transform,
    sh_degree=self.gaussians.active_sh_degree,
    campos=viewpoint_camera.camera_center,
    prefiltered=False,
    debug=False,
    antialiasing=False,  # Added this argument
)
```

In my current repository, the `diff-gaussian-rasterization` package was originally sourced from [here](https://github.com/ashawkey/diff-gaussian-rasterization/tree/8829d14f814fccdaf840b7b0f3021a616583c0a1). After the fix, it now uses the version from [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/tree/9c5c2028f6fbee2be239bc4c9421ff894fe4fbe0).  

Let me know if you have any further questions or run into other issues!  

Best Regards,
Ji Bo

**Comment by travellerCh** [comment]
@jibo27 
May I ask if this issue has been resolved? I'm encountering the same problem now, but this solution didn't work, and I'm still getting the error：
```
INFO:my_logger:Train Frame 0
Traceback (most recent call last):
  File "/data/ch/github/3DGS_Hierarchical_Training/run.py", line 51, in <module>
    trainer.hierarchical_training()
  File "/data/ch/github/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 698, in hierarchical_training
    self.compute_relative_pose(fidx, fidx-1) # rel_pose: view_idx_prev --> view_idx
  File "/data/ch/github/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 349, in compute_relative_pose
    return self.compute_relative_pose_vfi(view_idx, view_idx_prev)
  File "/data/ch/github/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 403, in compute_relative_pose_vfi
    self.train_single_image_3DGS(optim_opt, viewpoint_cam, pipe, gs_render=self.gs_render_local)
  File "/data/ch/github/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 291, in train_single_image_3DGS
    loss, rend_dict, psnr_train = self.train_step(gs_render,
  File "/data/ch/github/3DGS_Hierarchical_Training/trainer/ht3dgs_trainer.py", line 102, in train_step
    render_pkg = gs_render.render(
  File "/data/ch/github/3DGS_Hierarchical_Training/scene/gaussian_model_ht.py", line 872, in render
    out = rasterizer(
  File "/home/chenhao/anaconda3/envs/ht_3dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenhao/anaconda3/envs/ht_3dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenhao/anaconda3/envs/ht_3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 197, in forward
    return rasterize_gaussians(
  File "/home/chenhao/anaconda3/envs/ht_3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/chenhao/anaconda3/envs/ht_3dgs/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/chenhao/anaconda3/envs/ht_3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 84, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer, invdepths = _C.rasterize_gaussians(*args)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.67 GiB. GPU
```

> Hi,  你好，
> 
> Thank you for bringing this up! I was able to reproduce the error and resolve the issue.感谢您提出这个问题！我能够重现该错误并解决问题。
> 
> The problem stems from the `diff_gaussian_rasterization` package. To fix it, I uninstalled the current version and installed a new one from the [`gaussian-splatting`](https://github.com/graphdeco-inria/gaussian-splatting/tree/main) repository.问题源于`diff_gaussian_rasterization`包。为了解决这个问题，我卸载了当前版本并从[`gaussian-splatting`](https://github.com/graphdeco-inria/gaussian-splatting/tree/main)存储库安装了新版本。
> 
> Here are the steps I took to resolve the issue:以下是我解决该问题所采取的步骤：
> 
> **Step 1: Uninstall the current package and install the new one.步骤 1：卸载当前包并安装新包。**
> 
> git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive
> cd gaussian-splatting
> pip uninstall diff_gaussian_rasterization
> pip install submodules/diff-gaussian-rasterization
> **Step 2: Add the `antialiasing=False` argument.第 2 步：添加`antialiasing=False`参数。** I added this argument in the following [location](https://github.com/jibo27/3DGS_Hierarchical_Training/blob/main/scene/gaussian_model_ht.py#L809) in the code:我在代码中的以下[位置](https://github.com/jibo27/3DGS_Hierarchical_Training/blob/main/scene/gaussian_model_ht.py#L809)添加了此参数：
> 
> raster_settings = GaussianRasterizationSettings(
>     image_height=int(viewpoint_camera.image_height),
>     image_width=int(viewpoint_camera.image_width),
>     tanfovx=tanfovx,
>     tanfovy=tanfovy,
>     bg=self.bg_color if not invert_bg_color else 1 - self.bg_color,
>     scale_modifier=scaling_modifier,
>     viewmatrix=viewpoint_camera.world_view_transform,
>     projmatrix=viewpoint_camera.full_proj_transform,
>     sh_degree=self.gaussians.active_sh_degree,
>     campos=viewpoint_camera.camera_center,
>     prefiltered=False,
>     debug=False,
>     antialiasing=False,  # Added this argument
> )
> In my current repository, the `diff-gaussian-rasterization` package was originally sourced from [here](https://github.com/ashawkey/diff-gaussian-rasterization/tree/8829d14f814fccdaf840b7b0f3021a616583c0a1). After the fix, it now uses the version from [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/tree/9c5c2028f6fbee2be239bc4c9421ff894fe4fbe0).在我当前的存储库中， `diff-gaussian-rasterization`包最初来自[此处](https://github.com/ashawkey/diff-gaussian-rasterization/tree/8829d14f814fccdaf840b7b0f3021a616583c0a1)。修复后，它现在使用来自[此处的](https://github.com/graphdeco-inria/diff-gaussian-rasterization/tree/9c5c2028f6fbee2be239bc4c9421ff894fe4fbe0)版本。
> 
> Let me know if you have any further questions or run into other issues!如果您还有其他问题或遇到其他问题，请告诉我！
> 
> Best Regards,  此致， Ji Bo

**Comment by XLR-man** [comment]
yes, I have solved the problem according to the author's suggestion
